### ISSUE TITLE
Problems with v1.2.8

### ISSUE THREAD

**Issue by thePlaj** [aldelaro5/LiveSplit.BugFables#3]
After updating to the latest version I have several issues:

- The update prompt returns each time LiveSplit re-opens (including after selecting "yes" on the prompt). The autosplitter settings page shows version is 1.2.7.
- When LiveSplit and Bug Fables are both open, this is written to the log many times per second: `[2021-04-30 18:36:20] ShouldStart: Couldn't read the flags`
- #1 Start split seems to never trigger

**Comment by aldelaro5** [comment]
Fixed as of eab78ee85a0c5c0090ff6aea78771ce1653ef927
